name: movie_bonie
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # State Management
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.4.3+1

  # Data Class & Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Dependency Injection
  get_it: ^8.2.0

  # Routing
  go_router: ^16.2.1

  # Environment Variables
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.11
  freezed: ^3.2.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env